- job:
    name: python-cinderclient-functional-base
    abstract: true
    parent: devstack-tox-functional
    description: |
      Abstract job for defining devstack-based functional test jobs for
      python-cinderclient.  Jobs for particular python versions use this
      job as a parent, and control what verison of python is used by
      specifying a nodeset having the desired version of python as the
      system default.
    timeout: 4500
    required-projects:
      - openstack/cinder
      - openstack/python-cinderclient
    vars:
      openrc_enable_export: true
      devstack_localrc:
        VOLUME_BACKING_FILE_SIZE: 16G
        CINDER_QUOTA_VOLUMES: 25
        CINDER_QUOTA_BACKUPS: 25
        CINDER_QUOTA_SNAPSHOTS: 25
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*$
      - ^releasenotes/.*$
      - ^cinderclient/tests/unit/.*$

- job:
    name: python-cinderclient-functional-py310
    parent: python-cinderclient-functional-base
    # Python 3.10 is the default on Ubuntu 22.04 (Jammy)
    nodeset: openstack-single-node-jammy
    vars:
      devstack_localrc:
        # current master devstack no longer supports jammy as a platform
        # (change I796eddac96313584f4a), so we must force install it
        FORCE: 'yes'
      bindep_profile: test py310
      python_version: '3.10'
      tox_envlist: functional-py310

- job:
    name: python-cinderclient-functional-py313
    parent: python-cinderclient-functional-base
    # Python 3.13 is the default on Debian Trixie
    nodeset: devstack-single-node-debian-trixie
    vars:
      bindep_profile: test py310
      python_version: '3.13'
      tox_envlist: functional-py313

- project:
    vars:
      ensure_tox_version: '<4'
    templates:
      - check-requirements
      - lib-forward-testing-python3
      - openstack-cover-jobs
      - openstack-python3-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - python-cinderclient-functional-py310:
            # non-voting because devstack support on python 3.10
            # is no longer tested (see change I796eddac96313584f4a)
            voting: false
        - python-cinderclient-functional-py313
        - openstack-tox-pylint:
            voting: false
    gate:
      jobs:
        - python-cinderclient-functional-py313
