- job:
    name: python-cinderclient-functional-base
    abstract: true
    parent: devstack-tox-functional
    timeout: 4500
    required-projects:
      - openstack/cinder
      - openstack/python-cinderclient
    vars:
      openrc_enable_export: true
      devstack_localrc:
        USE_PYTHON3: true
        VOLUME_BACKING_FILE_SIZE: 16G
      devstack_local_conf:
        post-config:
          $CINDER_CONF:
            DEFAULT:
              quota_volumes: 25
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*$
      - ^releasenotes/.*$
      - ^cinderclient/tests/unit/.*$

- job:
    name: python-cinderclient-functional-py36
    parent: python-cinderclient-functional-base
    # need to specify a platform that has python 3.6 available
    nodeset: devstack-single-node-centos-8-stream
    vars:
      python_version: 3.6
      tox_envlist: functional-py36

- job:
    name: python-cinderclient-functional-py38
    parent: python-cinderclient-functional-base
    vars:
      python_version: 3.8
      tox_envlist: functional-py38

- project:
    templates:
      - check-requirements
      - lib-forward-testing-python3
      - openstack-cover-jobs
      - openstack-python3-xena-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - python-cinderclient-functional-py36
        - python-cinderclient-functional-py38
        - openstack-tox-pylint:
            voting: false
    gate:
      jobs:
        - python-cinderclient-functional-py36
        - python-cinderclient-functional-py38
