- job:
    name: python-cinderclient-functional
    parent: devstack
    run: playbooks/python-cinderclient-functional.yaml
    post-run: playbooks/post.yaml
    timeout: 4500
    required-projects:
      - openstack/cinder
      - openstack/python-cinderclient
    vars:
      devstack_localrc:
        USE_PYTHON3: true
        VOLUME_BACKING_FILE_SIZE: 16G

- project:
    templates:
      - check-requirements
      - lib-forward-testing
      - lib-forward-testing-python3
      - openstack-cover-jobs
      - openstack-python-jobs
      - openstack-python3-train-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - python-cinderclient-functional
        - openstack-tox-pylint:
            voting: false
