- job:
    name: cinderclient-dsvm-functional
    parent: legacy-dsvm-base
    run: playbooks/legacy/cinderclient-dsvm-functional/run.yaml
    post-run: playbooks/legacy/cinderclient-dsvm-functional/post.yaml
    timeout: 4200
    voting: false
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/cinder
      - openstack/python-cinderclient

- job:
    name: cinderclient-dsvm-functional-identity-v3-only
    parent: legacy-dsvm-base
    run: playbooks/legacy/cinderclient-dsvm-functional-identity-v3-only/run.yaml
    post-run: playbooks/legacy/cinderclient-dsvm-functional-identity-v3-only/post.yaml
    timeout: 4200
    voting: false
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/cinder
      - openstack/python-cinderclient


- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - publish-openstack-docs-pti
      - check-requirements
      - lib-forward-testing
      - release-notes-jobs-python3
    check:
      jobs:
        - cinderclient-dsvm-functional
        - cinderclient-dsvm-functional-identity-v3-only
        - openstack-tox-lower-constraints
        - openstack-tox-pylint:
            voting: false
    gate:
      jobs:
        - openstack-tox-lower-constraints
    post:
      jobs:
        - openstack-tox-cover
